### PR TITLE
Test change serialize/deserialize

### PR DESCRIPTION
**Pull request by secminhr**
1. Add tests for change serialize/deserialize
2. Fix `EventChangeTypes.EmitChange.__init__` argument mismatch
3. Add `ListChangeTypes.types` attribute for deserialize to work

2 and 3 may indicate that doing all this serializing thing by hand isn't wise and may result in errors.

### CODE REVIEW

**Comment by eri24816** [comment]
Thank you for writing the tests!

As for the issue of EventChangeTypes.EmitChange.__init__ , it seems like the method never receives forward_info as an argument in actual use. The EmitChange.forward_info's value is always set in EventTopic.notify_listeners(). But maybe adding the argument there is good for consistency.

**Comment by secminhr** [comment]
If that's the case, then it probably means that EmitChange has different serialization on client and server?

**Comment by eri24816** [comment]
I found that EmitChange and ReversedEmitChange are never serialized (except serialized to be printed out) because they are not sent to client.

**Comment by secminhr** [comment]
If it shouldn't be serialized, maybe we should make it raise `NotImplementedError` like `NullChange`?

**Comment by eri24816** [comment]
Looks like NullChange is redundant. It’s been not used since some previous commit.

For EmitChange, the serialize method is used for logging, so it should be implemented.

**Pull request merged**
